// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX8fPlpVKeuTJJ7azJ6-WKLve6hpB2dSs',
    appId: '1:70187796285:web:71fa73ce7c67a789092754',
    messagingSenderId: '70187796285',
    projectId: 'udayan-vats',
    authDomain: 'udayan-vats.firebaseapp.com',
    storageBucket: 'udayan-vats.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-I1o2DWGgdABqqLhHyuCSYOIRkLGS7XU',
    appId: '1:70187796285:android:9a1dab4a17eded16092754',
    messagingSenderId: '70187796285',
    projectId: 'udayan-vats',
    storageBucket: 'udayan-vats.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqP1T_TgACs2gbBn85DS6hMwaMNqki_-o',
    appId: '1:70187796285:ios:42932dd83c746d0d092754',
    messagingSenderId: '70187796285',
    projectId: 'udayan-vats',
    storageBucket: 'udayan-vats.appspot.com',
    iosClientId: '70187796285-e2ookg7a1v90b8re5uhhgpsn2jpnsgib.apps.googleusercontent.com',
    iosBundleId: 'hellocom.domain.gdsc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqP1T_TgACs2gbBn85DS6hMwaMNqki_-o',
    appId: '1:70187796285:ios:42932dd83c746d0d092754',
    messagingSenderId: '70187796285',
    projectId: 'udayan-vats',
    storageBucket: 'udayan-vats.appspot.com',
    iosClientId: '70187796285-e2ookg7a1v90b8re5uhhgpsn2jpnsgib.apps.googleusercontent.com',
    iosBundleId: 'hellocom.domain.gdsc',
  );
}
